
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: user-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userbackend
    username: root
    password: 123456
  redis:
    database: 3
    host: localhost
    port: 6379

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1 #逻辑已删除值（默认为1）
      logic-not-delete-value: 0


